# Generated by Django 4.2.5 on 2023-10-04 19:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nome_produto', models.CharField(max_length=255)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.compra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='Shop.CompraProduto', to='Shop.produto'),
        ),
    ]
